//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetProj
    {
        public Nullable<int> IDProj { get; set; }
        public int IDBugdet { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string RaisonBudget { get; set; }
        public Nullable<int> BudgetAttribueA { get; set; }
        public string BudgetAttribueANom { get; set; }
    
        public virtual EquipeProj EquipeProj { get; set; }
        public virtual FicheProj FicheProj { get; set; }
    }
}
