//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipeProj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipeProj()
        {
            this.BudgetProjs = new HashSet<BudgetProj>();
            this.TachesProjs = new HashSet<TachesProj>();
        }
    
        public Nullable<int> IDProj { get; set; }
        public Nullable<int> IDPerso { get; set; }
        public int IDMembreEquipe { get; set; }
        public string NomMembreEquipe { get; set; }
        public string RoleSurProj { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetProj> BudgetProjs { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual FicheProj FicheProj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TachesProj> TachesProjs { get; set; }
    }
}
