//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FicheProj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FicheProj()
        {
            this.BudgetProjs = new HashSet<BudgetProj>();
            this.EquipeProjs = new HashSet<EquipeProj>();
            this.TachesProjs = new HashSet<TachesProj>();
        }
    
        public int IDProj { get; set; }
        public string NomProj { get; set; }
        public string DescProj { get; set; }
        public string StatutProj { get; set; }
        public string CodeProj { get; set; }
        public string ChefProj { get; set; }
        public Nullable<int> ChefProjID { get; set; }
        public byte[] LogoProj { get; set; }
        public Nullable<System.DateTime> DateDebutProj { get; set; }
        public Nullable<System.DateTime> DateFinProj { get; set; }
        public Nullable<decimal> CibleProjet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetProj> BudgetProjs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipeProj> EquipeProjs { get; set; }
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TachesProj> TachesProjs { get; set; }
    }
}
