//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RlzProjectEntities : DbContext
    {
        public RlzProjectEntities()
            : base("name=RlzProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BudgetProj> BudgetProjs { get; set; }
        public virtual DbSet<EquipeProj> EquipeProjs { get; set; }
        public virtual DbSet<FicheProj> FicheProjs { get; set; }
        public virtual DbSet<Personnel> Personnels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TachesProj> TachesProjs { get; set; }
    }
}
