//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personnel()
        {
            this.EquipeProjs = new HashSet<EquipeProj>();
            this.FicheProjs = new HashSet<FicheProj>();
        }
    
        public int IDPerso { get; set; }
        public string NomPerso { get; set; }
        public string PrenomPerso { get; set; }
        public string PseudoPerso { get; set; }
        public string EmailPerso { get; set; }
        public string MotdepassePerso { get; set; }
        public Nullable<System.DateTime> DateNaissancePerso { get; set; }
        public string CivilitePerso { get; set; }
        public byte[] ImagePerso { get; set; }
        public string isAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipeProj> EquipeProjs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FicheProj> FicheProjs { get; set; }
    }
}
